### ISSUE TITLE
[refactor] rewrite dfget by using GoLang

### ISSUE THREAD

**Issue by lowzj** [alibaba/Dragonfly#43]
Using GoLang to rewrite the `dfget` in order to reduce the costs of multilingual development&maintenance, and resolve several problems of python-version `dfget`.

**TASKS LIST**:

- [x] refactor the directory structure of this project
    - [x] move all code sources of daemon sources to `./deamon/`
    - [x] use only one vendor in the whole project
    - [x] rewrite build scripts to support new project directory structure
- [x] check the code sources of Go
- [x] unit tests
    - [x] add unit-testing into CI flow
    - [x] add unit tests for `dfdaemon`
- [x] use GoLang to refactor `dfget`
    - [x] design the structure of `dfget`: version control, tests, CLI, exception, register, fetcher, server, rate limiter, net/file manager
    - [x] write build scripts for go-version `dfget`
    - [x] add unit tests for go-version `dfget`
   - [x] finish the completion of all modules
    - [x] delete python-version `dfget`

**Comment by caidongqing** [comment]
你好，golang重构 dfget是否已在目前的开源分支中了呢，我看了下应该还都是python吧？
另外，是不是 df-daemon getter后续都会用golang重构呢

**Comment by lowzj** [comment]
df-daemon目前已经是GoLang，getter正在重构中，之后的重构代码会放在`getter-refactor`分支中。重构完成后会将`getter-refactor`分支合并进`master`。

**Comment by caidongqing** [comment]
明白，非常感谢
